# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 135
        install-chromedriver: true
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj"
    - name: Build
      run: dotnet build "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj" --no-restore
    - name: Test
      run: dotnet test "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj" --no-build --verbosity normal
