# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 135
        install-chromedriver: true
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj"
    - name: Build
      run: dotnet build "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj" --no-restore
    - name: Download SCP Installer
      shell: pwsh
      env:
        PAT: ${{ secrets.SCP_REPO_PAT }}
      run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/bananegit/scpinstaller/main/scp.z01 -Headers @{Authorization="Token $($env:PAT)"} -OutFile scp.z01
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/bananegit/scpinstaller/main/scp.z02 -Headers @{Authorization="Token $($env:PAT)"} -OutFile scp.z02
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/bananegit/scpinstaller/main/scp.zip -Headers @{Authorization="Token $($env:PAT)"} -OutFile scp.zip
        7z x .\scp.zip
        Start-Process msiexec -ArgumentList "/package .\ScpInstaller.x64.msi /quiet" -wait
        Copy-Item -Path .\ScpPolicy.opg -Destination "C:\ProgramData\Skyhigh\SCP\Policy\Temp"
        
    - name: Test
      run: dotnet test "Artificial Intelligence/Tests/DeepSeekTests/DeepSeekTests.csproj" --no-build --verbosity normal
